image: archlinux
packages:
  - jekyll
oauth: pages.sr.ht/PAGES:RW
environment:
  site: mcritchlow.srht.site
tasks:
- build-site: |
    cd $site
    jekyll build
- package: |
    cd $site/_site
    tar -cvz . > ../../site.tar.gz
- upload: |
    acurl -f https://pages.sr.ht/publish/$site -Fcontent=@site.tar.gz
