image: archlinux
oauth: pages.sr.ht/PAGES:RW
environment:
  site: mcritchlow.srht.site
tasks:
- dependencies: |
    yay -Syu ruby-bundler
- build-site: |
    cd $site
    bundle install
    bundle exec jekyll build
- package: |
    cd _site
    tar -cvz . > ../../site.tar.gz
- upload: |
    acurl -f https://pages.sr.ht/publish/$site -Fcontent=@site.tar.gz
