image: archlinux
packages:
  - ruby-bundler
oauth: pages.sr.ht/PAGES:RW
environment:
  site: mcritchlow.srht.site
  domain: critchlow.xyz
tasks:
- build-site: |
    cd $site
    bundle install
    bundle exec jekyll build
- package: |
    cd $site/_site
    tar -cvz . > ../../site.tar.gz
- upload: |
    acurl -f https://pages.sr.ht/publish/$domain -Fcontent=@site.tar.gz
